import type { Metadata } from 'next';
import { ChatPannel, Sidebar } from '@/components/chat';
import styles from './styles.module.scss';
import createScn from '@/utils/scn';

const scn = createScn(styles);

export const metadata: Metadata = {
  title: 'Chat',
  description: 'Generated by create next app',
};

export default function ChatLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={`${scn('chat')}`}>
      <Sidebar />
      <div className={`${scn('chat__content')}`}>
        {/* <ChatPannel /> */}
        {children}
      </div>
    </main>
  );
}
