import userImage1 from '/public/assets/images/user-image-1.png';

export const users = [
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
  {
    image: userImage1,
    name: 'Sabir Nawaz',
    message: 'Hello World',
    time: '3:14',
    messagesCount: 234,
  },
];
